server:
    port: 8081
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/test
        username: postgres
        password: fanxfan
    jpa:
        open-in-view: true
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    redis:
        host: 127.0.0.1
        port: 6378
        password: 123456
        # 连接超时时间（记得添加单位，Duration）
        timeout: 10000ms
        # Redis默认情况下有16个分片，这里配置具体使用的分片
        # database: 0
        lettuce:
            pool:
                # 连接池最大连接数（使用负值表示没有限制） 默认 8
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
                max-wait: -1ms
                # 连接池中的最大空闲连接 默认 8
                max-idle: 8
                # 连接池中的最小空闲连接 默认 0
                min-idle: 0
    cache:
        # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
        type: redis
justauth:
    cache:
        type: default
    type:
        GITEE:
            client-id: xxxx12345
            client-secret: xxxx12345
            redirect-uri: http://127.0.0.1:8081/oauth/gitee/callback
        GITHUB:
            client-id: xxxx12345
            client-secret: xxxx12345
            redirect-uri: http://127.0.0.1:8081/oauth/github/callback
