server:
    port: 8081
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://127.0.0.1:3307/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: fanxfan
        filters: stat,wall
        maxActive: 20
        maxIdle: 10
        minIdle: 10
        initialSize: 10
        validationQuery: select 1
    jpa:
        open-in-view: true
        show-sql: true
        generate-ddl: true
#        database: mariadb
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl